Alimenta-Ação/Projeto_AlimentaAcao/AlimentaAcao/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

Alimenta-Ação/Projeto_AlimentaAcao/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('doe', views.doe, name='doe'),
    path('nossotime/', views.nossotime, name='nossotime'),
    path('entreemcontato', views.contato, name='contato'),
    path('avaliacao/', views.avaliacao, name='avaliacao'),
    path('login/', views.loginONG, name='login'),
    path('doe/validacao',views.doacao, name='validacao'),
    path('doe/validacao/concluida', views.validacaoCon, name='validacaocon'),
    # path('recuperacaologin/'),
    path('indexOng/publicacao', views.paginaONG, name='ong'),
    path('indexOng', views.indexOng, name='indexong'),
    path('indexOng/ModificarPublicacao', views.ModificaCampanha, name='modifica'),
    path('indexOng/ModificarPublicacao/atualizar', views.atualizar, name='atualiza'),
]

Alimenta-Ação/Projeto_AlimentaAcao/core/forms.py
from django import forms
from django.core.exceptions import ValidationError

class ONGForm(forms.Form):
  Nome = forms.CharField(max_length=50)
  Telefone = forms.CharField(max_length=15)
  Email = forms.EmailField(max_length=100)
  Senha = forms.CharField(max_length=128, widget=forms.PasswordInput)
  CNPJ = forms.CharField(max_length=15)

  def clean_nome(self):
    nome = self.cleaned_data.get['Nome']
    return nome.title()

  def clean_telefone(self):
    telefone = self.cleaned_data.get['Telefone']
    if len(telefone) == 11:
      return telefone
    raise ValidationError('Número de Telefone invávlido')

  def clean_email(self):
    email = self.cleaned_data.get['Email']
    return email
  
  def clean_cnpj(self):
    cnpj = self.cleaned_data["CNPJ"]
    if len(cnpj) == 11:
      return cnpj
    raise ValidationError('tem que ter 11 caracteres')
  
  def clean_senha(self):
    senha = self.cleaned_data["senha"]
    return senha
    
class ONGLoginForm(forms.Form):
  CNPJ = forms.CharField(max_length=15)
  Senha = forms.CharField(max_length=128, widget=forms.PasswordInput)
  
  def clean_cnpj(self):
    cnpj = self.cleaned_data["CNPJ"]
    if len(cnpj) == 11:
      return cnpj
    raise ValidationError('tem que ter 11 caracteres')
  
  def clean_senha(self):
    senha = self.cleaned_data["senha"]
    return senha
  
class PubliONGForm(forms.Form): 
  Mensagem = forms.CharField(max_length=1028, widget=forms.Textarea)
  Meta = forms.FloatField()
  Nome = forms.CharField(max_length=50)
  DataExpiracao = forms.DateField()
  Locais = forms.CharField()
  
  def clean_mensagem(self):
    mensagem = self.cleaned_data["mensagem"]
    return mensagem
  
  def clean_metaArrecadacao(self):
    metaArrecadacao = self.cleaned_data["metaArrecadacao"]
    if metaArrecadacao > 0:
      return metaArrecadacao
    return ValidationError("tem que ser um valor positivo")
  
  def clean_nome(self):
    nome = self.cleaned_data["nome"]
    return nome.title()
  
  def clean_dataExpiracao(self):
    dataExpi = self.cleaned_data["dataExpi"]
    return dataExpi
  
  def clean_locaisAjuda(self):
    locais = self.cleaned_data["locais"]
    return locais
  

class DoacaoForm(forms.Form):
  Nome = forms.CharField(max_length=15)
  Data = forms.DateField()
  Valor = forms.CharField(max_length=10)
    
  def clean_nome(self):
    nome = self.cleaned_data['Nome']
    return nome.title()
  
  def clean_data(self):
    data = self.cleaned_data["Data"]
    return data

  def clean_valor(self):
    valor = self.cleaned_data["Valor"]
    return valor
  
class ValidacaoForm(forms.Form):
  Nome_Cartao = forms.CharField(max_length=70)
  Num_Cartao = forms.CharField(max_length=50)
  Mes_Cartao = forms.IntegerField()
  Ano_Cartao = forms.IntegerField()
  CVV = forms.IntegerField()
  
  def clean_nome_cart(self):
    nome_cart = self.cleaned_data["nome_cart"]
    return nome_cart
  
  def clean_num_cart(self):
    num_cart = self.cleaned_data["num_cart"]
    return num_cart
  
  def clean_ano_cart(self):
    ano_cart = self.cleaned_data["ano_cart"]
    return ano_cart
  
  def clean_mes_cart(self):
    mes_cart = self.cleaned_data["mes_cart"]
    return mes_cart
  
  def clean_cvv(self):
    cvv = self.cleaned_data["cvv"]
    return cvv
  

Alimenta-Ação/Projeto_AlimentaAcao/core/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse
from core.forms import ONGForm, ONGLoginForm, PubliONGForm, DoacaoForm, ValidacaoForm
from .services.Repositories.ONGRepository import ONGRepository
from .services.Repositories.DoacaoRepository import DoacaoRepository
from .services.Repositories.CampanhaRepository import CampanhaRepository
from .services.ConnectionService import ConnectionService
from .services.MongoService import MongoService
from django.contrib import messages
from bson.objectid import ObjectId
import datetime

def index(request):
  if request.method == "GET":
    conexao = ConnectionService()
    banco = MongoService(conexao, "AlimentaAcao")
    repository = CampanhaRepository(banco)
    campanha = {
      'campanhas': repository.find_many({})
    }
    print(campanha)
    return render(request, "index.html", campanha)
  return HttpResponseRedirect(reverse('core:index'))

def doe(request):
  id = request.GET.get('id')
  conexao = ConnectionService()
  banco = MongoService(conexao, "AlimentaAcao")
  repositoryDoa = DoacaoRepository(banco)
  repositoryCamp = CampanhaRepository(banco)
  
  campanha = repositoryCamp.find_one({'_id': ObjectId(id)})
  if request.method == "POST":
    form = DoacaoForm(request.POST)
    if form.is_valid():
      query = {
        'doador': form.cleaned_data.get('Nome'),
        'valor': form.cleaned_data.get('Valor'),
        'data_envio': str(form.cleaned_data.get('Data'))
      }
      repositoryDoa.insert_one(query)
      doar = repositoryDoa.find_one(query)
    return HttpResponseRedirect(f'{reverse('core:validacao')}?id={doar['_id']}')
  contexto = {
    'titulo': campanha['titulo'],
    'descricao': campanha['descricao'],
    'locais': campanha['locais'],
  }
  return render(request, "doe.html", contexto)

def doacao(request):
  id = request.GET.get('id')
  conexao = ConnectionService()
  banco = MongoService(conexao, "AlimentaAcao")
  repository = DoacaoRepository(banco)
  query = {
    '_id': ObjectId(id)
  }
  if request.method == "POST":
    form = ValidacaoForm(request.POST)
    print(form.is_valid())
    if 'validar' in request.POST:
      if form.is_valid():
        valores = {
          "Nome_Cartao": form.cleaned_data.get('Nome_Cartao'),
          "Num_Cartao": form.cleaned_data.get('Num_Cartao'),
          "Mes_Cartao": form.cleaned_data.get('Mes_Cartao'),
          "Ano_Cartao": form.cleaned_data.get('Ano_Cartao'),
          "CVV": form.cleaned_data.get('CVV'),
          'id_campanha': id,
        }
        print(query)
        print(valores)
        repository.update_one(query, valores)
        return HttpResponseRedirect(reverse('core:validacaocon'))
    elif 'cancelar' in request.POST:
      repository.delete_one(query)
      return HttpResponseRedirect(reverse('core:validacaocon'))
  doador = repository.find_one(query)
  contexto = {
    "DoacaoForm": ValidacaoForm(),
    'valor': doador['valor'],
  }
  return render(request, "validacao.html", contexto)

def validacaoCon(request):
  if request.method == "GET":
    return render(request, "validacaoconcluida.html")
  return HttpResponseRedirect(reverse('core:validacaocon'))
  
def nossotime(request):
  if request.method == "GET":
    return render(request, "nossotime.html")
  return HttpResponseRedirect(reverse('core:nossotime'))

def contato(request):
  if request.method == "GET":
    return render(request, "contato.html")
  return HttpResponseRedirect(reverse('core:contato'))

def avaliacao(request):
  if request.method == "GET":
    return render(request, "avaliacao.html")
  return HttpResponseRedirect(reverse('core:avaliacao'))

def loginONG(request):
  if request.method == "POST":
    if 'cadastro-submit' in request.POST:
      form = ONGForm(request.POST)
      if form.is_valid():
        conexao = ConnectionService()
        banco = MongoService(conexao, "AlimentaAcao")
        repository = ONGRepository(banco)
        existe = repository.validar_cnpj(form.cleaned_data.get('CNPJ'))
        if existe:
          repository.insert_one(form.cleaned_data)
          usuario = repository.login(form.cleaned_data.get('CNPJ'), form.cleaned_data.get('Senha'))
          if usuario is not None:
            id = usuario['_id']
            return HttpResponseRedirect(f'{reverse('core:indexong')}?id={id}')
          else:
            messages.success(request, "CNPJ ou Senha inválido!!")
        else:
          messages.success(request, "Esse usuário já existe, tente novamente!!!")
    elif 'login-submit' in request.POST:
      form = ONGLoginForm(request.POST)
      if form.is_valid():
        conexao = ConnectionService()
        banco = MongoService(conexao, "AlimentaAcao")
        repository = ONGRepository(banco)
        usuario = repository.login(form.cleaned_data.get('CNPJ'), form.cleaned_data.get('Senha'))
        if usuario is not None:
          id = usuario['_id']
          return HttpResponseRedirect(f'{reverse('core:indexong')}?id={id}')
        else:
          messages.success(request, "CNPJ ou Senha inválido!!")
  contexto = {
    'cadastro_form': ONGForm(),
    'login_form': ONGLoginForm(),
  }
  return render(request, "login.html", contexto)

def indexOng(request):
  id = request.GET.get('id')
  conexao = ConnectionService()
  banco = MongoService(conexao, "AlimentaAcao")
  repositoryOng = ONGRepository(banco)

  ong = repositoryOng.find_one({'_id': ObjectId(id)})
  contexto = {
    'nome_ong': ong['Nome'],
    'id': ong['_id'],
  }
  return render(request, "indexong.html", contexto)

def paginaONG(request):
  id = request.GET.get('id')
  conexao = ConnectionService()
  banco = MongoService(conexao, "AlimentaAcao")
  repositoryOng = ONGRepository(banco)
  repositoryPubl = CampanhaRepository(banco)
  
  Ong = repositoryOng.find_one({'_id': ObjectId(id)})
  if Ong is not None:
    if request.method == 'POST':
      form = PubliONGForm(request.POST)
      if form.is_valid():
        cidades = form.cleaned_data.get('Locais')
        locais = cidades.split(",")
        query = {
          'titulo': form.cleaned_data.get('Nome'),
          'meta': float(form.cleaned_data.get('Meta')),
          'data_inicio': str(datetime.date.today()),
          'data_fim': str(form.cleaned_data.get('DataExpiracao')),
          'locais': locais,
          'descricao': form.cleaned_data.get('Mensagem'),
          'CNPJ_Ong': Ong['CNPJ'],
          'status': True,
        }
        repositoryPubl.insert_one(query)
    contexto = {
      'campanha_form': PubliONGForm(),
      'email': Ong['Email'],
      'telefone': Ong['Telefone']
    }
    return render(request, "publicarong.html", contexto)
  else:
    return HttpResponseRedirect(reverse('core:index'))
  
def ModificaCampanha(request):
  id = request.GET.get('id')
  conexao = ConnectionService()
  banco = MongoService(conexao, "AlimentaAcao")
  repository = CampanhaRepository(banco)
  repositoryOng = ONGRepository(banco)
  repositoryDoa = DoacaoRepository(banco)
  
  ong = repositoryOng.find_one({'_id': ObjectId(id)})
  campanha = repository.find_one({'CNPJ_Ong': ong['CNPJ']})
  if request.method == "GET":
    campanha = {
      'campanhas': repository.find_many({}),
      'nome_ong': ong['Nome'],
    }
    return render(request, "modificar.html", campanha)
  elif request.method == "POST":
    if 'editar' in request.POST:
      HttpResponseRedirect(f'{reverse('core:atualiza')}?id={campanha['_id']}')
    elif 'deletar' in request.POST:
      repository.delete_one({'_id': campanha['_id']})
      repositoryDoa.delete_many({'id_campanha': campanha['_id']})
      
  return HttpResponseRedirect(f'{reverse('core:modifica')}?id={id}')

def atualizar(request):
  id = request.GET.get('id')
  conexao = ConnectionService()
  banco = MongoService(conexao, "AlimentaAcao")
  repositoryOng = ONGRepository(banco)
  repositoryPubl = CampanhaRepository(banco)
  query = {
    '_id': ObjectId(id)
  }
  
  Publi = repositoryPubl.find_one(query)
  if Ong is not None:
    if request.method == 'POST':
      form = PubliONGForm(request.POST)
      if form.is_valid():
        cidades = form.cleaned_data.get('Locais')
        locais = cidades.split(",")
        valores = {
          'titulo': form.cleaned_data.get('Nome'),
          'meta': float(form.cleaned_data.get('Meta')),
          'data_fim': str(form.cleaned_data.get('DataExpiracao')),
          'locais': locais,
          'descricao': form.cleaned_data.get('Mensagem'),
        }
        repositoryPubl.update_one(query, valores)
  else:
    return HttpResponseRedirect(f'{reverse('core:modifica')}?id={Publi['id_campanha']}')
  contexto = {
    'titulo': Publi['titulo'],
    'meta': Publi['meta'],
    'data_fim': Publi['data_fim'],
    'locais': Publi['locais'],
    'descricao': Publi['descricao']
  }
  return render(request, "atualiza.html", contexto)

Alimenta-Ação/Projeto_AlimentaAcao/core/templates/avaliacao.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
   <head>
      <meta charset="utf-8">
      <title>Avaliação</title>
      <!-- custom css link -->
      <link rel="stylesheet" href="{% static 'css/avaliacao.css' %}">
      <link rel="stylesheet" href="{% static 'css/responsivo.css' %}">
      <!-- google font link -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
      <link
         href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Roboto:wght@300;400;500;700&family=Oswald:wght@600&display=swap"
         rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
   </head>
   <body>
      <!-- HEADER -->
      <header class="header" data-header>
         <div class="container">
            <h1>
               <a href="{% url 'core:index' %}" class="logo">Alimenta Ação</a>
            </h1>
            <button class="nav-open-btn" aria-label="Open Menu" data-nav-open-btn>
               <ion-icon name="menu-outline"></ion-icon>
            </button>
            <nav class="navbar" data-navbar>
               <button class="nav-close-btn" aria-label="Close Menu" data-nav-close-btn>
                  <ion-icon name="close-outline"></ion-icon>
               </button>
               <a href="{% url 'core:index' %}" class="logo">Alimenta Ação</a>
               <ul class="navbar-list">
                  <li>
                     <a href="{% url 'core:index' %}" class="navbar-link" data-nav-link>
                        <span>Menu</span>
                        <ion-icon name="chevron-forward-outline" aria-hidden="true"></ion-icon>
                     </a>
                  </li>
                  <li>
                  <li>
                     <a href="{% url 'core:index' %}" class="navbar-link" data-nav-link id="link-sobre">
                        <span>Sobre</span>
                        <ion-icon name="chevron-forward-outline" aria-hidden="true"></ion-icon>
                     </a>
                  </li>
                  </li>
                  <li>
                     <a href="{% url 'core:index' %}" class="navbar-link" data-nav-link id="link-servicos">
                        <span>Serviços</span>
                        <ion-icon name="chevron-forward-outline" aria-hidden="true"></ion-icon>
                     </a>
                  </li>
                  <li class="navbar-item has-submenu" data-nav-item>
                     <a href="{% url 'core:index' %}" class="navbar-link" data-nav-link>Páginas<i class="bi bi-caret-down-fill"></i></a>
                     <ul class="submenu">
                        <li class="dropdown-item"><a href="{% url 'core:index' %}" id="link-doar">Doar</a></li>
                        <li class="dropdown-item"><a href="{% url 'core:nossotime' %}">Nosso time</a></li>
                        <li class="dropdown-item"><a href="{% url 'core:index' %}" id="link-depoimentos">Depoimentos</a></li>
                        <li class="dropdown-item"><a href="{% url 'core:avaliacao' %}">Nos Avalie</a></li>
                     </ul>
                  </li>
                  <li>
                     <a href="{% url 'core:contato' %}" class="navbar-link" data-nav-link>
                        <span>Entre em contato</span>
                        <ion-icon name="chevron-forward-outline" aria-hidden="true"></ion-icon>
                     </a>
                  </li>
                  <li>
                     <a href="{% url 'core:login' %}" class="navbar-link" data-nav-link>
                        <span>Login</span>
                        <ion-icon name="chevron-forward-outline" aria-hidden="true"></ion-icon>
                     </a>
                  </li>
               </ul>
            </nav>
            <div class="header-action">
               <button id="doarBtn" class="btn btn-primary">
                  <span>Doe agora!</span>
                  <ion-icon name="heart-outline" aria-hidden="true"></ion-icon>
               </button>
            </div>
         </div>
      </header>
      <div class="avaliacao">
         <div class="post">
            <div class="text">Obrigado por nos avaliar!</div>
            <button class="edit">EDITAR</button>
            <button type="edit2" onclick="window.location.href='index.html'">SALVAR</button>
         </div>
         <div class="star-widget">
            <input type="radio" name="rate" id="rate-5">
            <label for="rate-5" class="fas fa-star"></label>
            <input type="radio" name="rate" id="rate-4">
            <label for="rate-4" class="fas fa-star"></label>
            <input type="radio" name="rate" id="rate-3">
            <label for="rate-3" class="fas fa-star"></label>
            <input type="radio" name="rate" id="rate-2">
            <label for="rate-2" class="fas fa-star"></label>
            <input type="radio" name="rate" id="rate-1">
            <label for="rate-1" class="fas fa-star"></label>
            <form action="#">
               <header></header>
               <div class="textarea">
                  <textarea cols="30" placeholder="Descreva sua experiência.."></textarea>
               </div>
               <div class="btn2">
                  <button type="submit">Publicar</button>
               </div>
            </form>
         </div>
      </div>
      <script src="{% static 'js/avaliacao.js' %}"></script>
      <script src="{% static 'js/index.js' %}"></script>
   </body>
</html>

Alimenta-Ação/Projeto_AlimentaAcao/core/templates/nossotime.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Alimenta Ação</title>
      <!-- favicon -->
      <link rel="shortcut icon" href="./favicon.svg" type="image/svg+xml">
      <!-- custom css link -->
      <link rel="stylesheet" href="{% static 'css/nossotime.css' %}">
      <link rel="stylesheet" href="{% static 'css/responsivo.css' %}">
      <!-- google font link -->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css" rel="stylesheet">
      <link
         href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Roboto:wght@300;400;500;700&family=Oswald:wght@600&display=swap"
         rel="stylesheet">
      <!-- Link para a biblioteca de ícones Font Awesome -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
   </head>
   <body>
      <!-- HEADER -->
      <header class="header" data-header>
         <div class="container">
            <h1>
               <a href="{% url 'core:index' %}" class="logo">Alimenta Ação</a>
            </h1>
            <button class="nav-open-btn" aria-label="Open Menu" data-nav-open-btn>
               <ion-icon name="menu-outline"></ion-icon>
            </button>
            <nav class="navbar" data-navbar>
               <button class="nav-close-btn" aria-label="Close Menu" data-nav-close-btn>
                  <ion-icon name="close-outline"></ion-icon>
               </button>
               <a href="{% url 'core:index' %}" class="logo">Alimenta Ação</a>
               <ul class="navbar-list">
                  <li>
                     <a href="{% url 'core:index' %}" class="navbar-link" data-nav-link>
                        <span>Menu</span>
                        <ion-icon name="chevron-forward-outline" aria-hidden="true"></ion-icon>
                     </a>
                  </li>
                  <li>
                  <li>
                     <a href="{% url 'core:index' %}" class="navbar-link" data-nav-link id="link-sobre">
                        <span>Sobre</span>
                        <ion-icon name="chevron-forward-outline" aria-hidden="true"></ion-icon>
                     </a>
                  </li>
                  </li>
                  <li>
                     <a href="{% url 'core:index' %}" class="navbar-link" data-nav-link id="link-servicos">
                        <span>Serviços</span>
                        <ion-icon name="chevron-forward-outline" aria-hidden="true"></ion-icon>
                     </a>
                  </li>
                  <li class="navbar-item has-submenu" data-nav-item>
                     <a href="{% url 'core:index' %}" class="navbar-link" data-nav-link>Páginas<i class="bi bi-caret-down-fill"></i></a>
                     <ul class="submenu">
                        <li class="dropdown-item"><a href="{% url 'core:index' %}" id="link-doar">Doar</a></li>
                        <li class="dropdown-item"><a href="{% url 'core:nossotime' %}">Nosso time</a></li>
                        <li class="dropdown-item"><a href="{% url 'core:index' %}" id="link-depoimentos">Depoimentos</a></li>
                        <li class="dropdown-item"><a href="{% url 'core:avaliacao' %}">Nos Avalie</a></li>
                     </ul>
                  </li>
                  <li>
                     <a href="{% url 'core:contato' %}" class="navbar-link" data-nav-link>
                        <span>Entre em contato</span>
                        <ion-icon name="chevron-forward-outline" aria-hidden="true"></ion-icon>
                     </a>
                  </li>
                  <li>
                     <a href="{% url 'core:login' %}" class="navbar-link" data-nav-link>
                        <span>Login</span>
                        <ion-icon name="chevron-forward-outline" aria-hidden="true"></ion-icon>
                     </a>
                  </li>
               </ul>
            </nav>
            <div class="header-action">
               <button id="doarBtn" class="btn btn-primary">
                  <span>Doe agora!</span>
                  <ion-icon name="heart-outline" aria-hidden="true"></ion-icon>
               </button>
            </div>
         </div>
      </header>
      <div class="wrapper">
         <div class="title">
            <h4>Nosso Time</h4>
         </div>
         <div class="card_Container">
            <div class="card">
               <div class="imbBx">
                  <img src="./image/pic01.jpg" alt="">
               </div>
               <div class="content">
                  <div class="contentBx">
                     <h3>Wesley Kilian <br><span>Front End</span></h3>
                  </div>
                  <ul class="sci">
                     <li style="--i: 1">
                        <a href="#"><i class="fa-brands fa-instagram"></i></a>
                     </li>
                     <li style="--i: 2">
                        <a href="#"><i class="fa-brands fa-github"></i></a>
                     </li>
                     <li style="--i: 3">
                        <a href="#"><i class="fa-brands fa-linkedin-in"></i></a>
                     </li>
                  </ul>
               </div>
            </div>
            <div class="card">
               <div class="imbBx">
                  <img src="./image/pic02.jpg" alt="">
               </div>
               <div class="content">
                  <div class="contentBx">
                     <h3>William Fonseca <br><span>Back End</span></h3>
                  </div>
                  <ul class="sci">
                     <li style="--i: 1">
                        <a href="#"><i class="fa-brands fa-instagram"></i></a>
                     </li>
                     <li style="--i: 2">
                        <a href="#"><i class="fa-brands fa-github"></i></a>
                     </li>
                     <li style="--i: 3">
                        <a href="#"><i class="fa-brands fa-linkedin-in"></i></a>
                     </li>
                  </ul>
               </div>
            </div>
            <div class="card">
               <div class="imbBx">
                  <img src="./image/pic03.jpg" alt="">
               </div>
               <div class="content">
                  <div class="contentBx">
                     <h3>Vitor Eduardo<br><span>Back End</span></h3>
                  </div>
                  <ul class="sci">
                     <li style="--i: 1">
                        <a href="#"><i class="fa-brands fa-instagram"></i></a>
                     </li>
                     <li style="--i: 2">
                        <a href="#"><i class="fa-brands fa-github"></i></a>
                     </li>
                     <li style="--i: 3">
                        <a href="#"><i class="fa-brands fa-linkedin-in"></i></a>
                     </li>
                  </ul>
               </div>
            </div>
            <div class="card">
               <div class="imbBx">
                  <img src="./image/pic04.jpg" alt="">
               </div>
               <div class="content">
                  <div class="contentBx">
                     <h3>Thiago<br><span>Banco de Dados</span></h3>
                  </div>
                  <ul class="sci">
                     <li style="--i: 1">
                        <a href="#"><i class="fa-brands fa-instagram"></i></a>
                     </li>
                     <li style="--i: 2">
                        <a href="#"><i class="fa-brands fa-github"></i></a>
                     </li>
                     <li style="--i: 3">
                        <a href="#"><i class="fa-brands fa-linkedin-in"></i></a>
                     </li>
                  </ul>
               </div>
            </div>
            <div class="card">
               <div class="imbBx">
                  <img src="./image/pic04.jpg" alt="">
               </div>
               <div class="content">
                  <div class="contentBx">
                     <h3>Miran<br><span></span></h3>
                  </div>
                  <ul class="sci">
                     <li style="--i: 1">
                        <a href="#"><i class="fa-brands fa-instagram"></i></a>
                     </li>
                     <li style="--i: 2">
                        <a href="#"><i class="fa-brands fa-github"></i></a>
                     </li>
                     <li style="--i: 3">
                        <a href="#"><i class="fa-brands fa-linkedin-in"></i></a>
                     </li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
      <script src="{% static 'js/index.js' %}"></script>
      <script src="https://cdn.jsdelivr.net/npm/swiper@6/swiper-bundle.min.js"></script>
      <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
      <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
   </body>
</html>